const creativeDetails = `<g stroke-linecap="round" stroke-linejoin="round"><rect x="7" y="7" width="66" height="66" rx="20" stroke="#d1c4ff" stroke-opacity=".25"/><path d="M29 65c8-1 10 5 18 2s10-6 15-4" stroke="#5ce0c7" stroke-width="1.8" opacity=".7"/><circle cx="15" cy="43" r="1.6" fill="#ffce79"/><circle cx="18" cy="48" r="1.6" fill="#f1b4e6"/><circle cx="14" cy="53" r="1.6" fill="#5ce0c7"/><path d="m33 18 2-3m-5 2-1-3m7 7 3-1" stroke="#e0d7ff" stroke-width="1" opacity=".75"/><g transform="translate(57 11) rotate(12)"><rect width="12" height="9" rx="2" fill="#a997f1" fill-opacity=".3" stroke="#d7caff" stroke-width=".8"/><circle cx="8.5" cy="2.8" r="1" fill="#ffce79"/><path d="m2 7 3-3 3 3 2-2" stroke="#b9fff0" stroke-width=".8"/></g><g transform="translate(41 58) rotate(-8)"><rect width="11" height="8" rx="1.5" fill="#362d85" stroke="#c9bbff" stroke-width=".7"/><path d="m4.5 2 3 2-3 2Z" fill="#ffce79"/><path d="M1.5 2h1m-1 4h1M8.5 2h1m-1 4h1" stroke="#c9bbff" stroke-width=".6"/></g><circle cx="65" cy="41" r="1" fill="#b9fff0"/><circle cx="36" cy="10" r=".7" fill="#ffce79"/><circle cx="9" cy="35" r=".7" fill="#f1b4e6"/><path d="m69 60 1.5 1.5m-1.5 0 1.5-1.5" stroke="#ffce79" stroke-width=".8"/></g>`;

const evolvingSketch = `<svg viewBox="0 0 480 160" fill="none" aria-hidden="true" focusable="false"><g class="sketch-lines" stroke-linecap="round" stroke-linejoin="round"><path class="draw-line stage-one" pathLength="1" d="M55 132h364M95 126l10-105h210l-10 105H95Z" stroke="#b4a4da" stroke-width="2"/><path class="draw-line stage-two" pathLength="1" d="m119 105 39-44 29 27 34-48 53 65H119Zm112-73a9 9 0 1 0 18 0 9 9 0 0 0-18 0" stroke="#7150c8" stroke-width="2.5"/><path class="draw-line stage-three" pathLength="1" d="m327 102 39-76 12 6-39 76-15 11 3-17Zm36-70 12 6M327 102l12 6m-15 11 4-7" stroke="#0b8f82" stroke-width="2.5"/><path class="draw-line stage-four" pathLength="1" d="M380 114c-15-6-22-27-9-38 10-8 18-1 27-2 13-2 30 16 23 28-4 7-13 1-17 5-3 4-10 11-24 7ZM67 54l3-8 8-3-8-3-3-8-3 8-8 3 8 3 3 8Zm265-38 2-6 6-2-6-2-2-6-2 6-6 2 6 2 2 6" stroke="#b97527" stroke-width="2"/><path class="draw-line stage-five" pathLength="1" d="M111 140c30-8 70 9 102 0s58 2 83-3m-172-4 50-5m72 6 18-2M49 92l-8-5m14-3-3-7m352-42 8-5m-5 16 9-1" stroke="#a270c4" stroke-width="1.5"/></g><g class="sketch-color"><path d="m121 104 37-41 28 28 35-49 51 62H121Z" fill="#9fdcd4" fill-opacity=".5"/><path d="m188 92 33-50 51 62h-44l-16-20-24 8Z" fill="#c8b5ed" fill-opacity=".8"/><circle cx="240" cy="32" r="8" fill="#ffd18c"/><circle cx="378" cy="88" r="4" fill="#e99cae"/><circle cx="391" cy="82" r="4" fill="#9e85e3"/><circle cx="407" cy="88" r="4" fill="#57bdb0"/><circle cx="411" cy="99" r="3" fill="#f0bb64"/></g></svg>`;

export function studioPage() {
  return `<!doctype html>
<html lang="sl">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Content Studio</title>
  <style>
    :root{color-scheme:light;--bg:#f3f5f7;--paper:#ffffff;--ink:#121417;--muted:#667085;--line:#d7dee8;--accent:#8a3f2d;--green:#117466;--blue:#dd7a73;--amber:#b86b1c;--soft:#edf1f5;--danger:#b42318;--shadow:0 10px 28px rgba(18,24,33,.08)}
    *{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:linear-gradient(180deg,#eef3f6 0,#f8fafb 240px,#f3f5f7 100%);color:var(--ink)}
    main{width:min(1380px,calc(100% - 24px));margin:0 auto;padding:12px 0 28px}header{display:flex;justify-content:space-between;align-items:center;gap:14px;border:1px solid #cfd8e5;background:linear-gradient(135deg,#ffffff 0,#f8fbfa 52%,#fff6ef 100%);border-radius:8px;padding:14px 16px;margin-bottom:10px;box-shadow:var(--shadow)}
    h1{font-size:30px;line-height:1;margin:0;letter-spacing:0}.eyebrow{display:inline-flex;align-items:center;width:max-content;border:1px solid #c7d8d3;background:#eef8f5;color:#117466;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:820;margin-bottom:7px}h2{font-size:13px;text-transform:uppercase;letter-spacing:.08em;margin:0 0 10px;color:#2f3a48;display:flex;align-items:center;gap:7px}h2:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--accent)}p{color:var(--muted);margin:5px 0 0;line-height:1.42}a,button,input,select,textarea{font:inherit}a{color:var(--green);font-weight:760;text-decoration:none}
    button,.button{min-height:36px;border:1px solid var(--accent);border-radius:8px;padding:0 12px;background:var(--accent);color:#fff;font-size:13px;font-weight:800;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;gap:7px;box-shadow:0 1px 1px rgba(18,20,23,.06)}button:hover,.button:hover{filter:brightness(.98);transform:translateY(-1px)}
    button.secondary,.button.secondary{background:#fff;color:var(--ink);border-color:var(--line)}button.blue{background:var(--blue);border-color:var(--blue)}button.green{background:var(--green);border-color:var(--green)}button:disabled{opacity:.6;cursor:progress;transform:none}
    .actions,.tabs,.tools{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.layout{display:grid;grid-template-columns:304px minmax(0,1fr) 336px;gap:12px;align-items:start}.panel{background:rgba(255,255,255,.96);border:1px solid var(--line);border-radius:8px;padding:13px;box-shadow:var(--shadow)}
    label{display:grid;gap:5px;color:#596579;font-size:12px;font-weight:760;margin-bottom:8px}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--ink);padding:9px 10px}input:focus,select:focus,textarea:focus{outline:3px solid rgba(35,95,216,.14);border-color:#8ba7f7}textarea{resize:vertical;line-height:1.5}.prompt{min-height:82px}.post{min-height:450px;font-size:15.5px;background:#fffdf9}
    .two{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.image{aspect-ratio:4/5;border-radius:8px;background:linear-gradient(135deg,#e8eef3,#fffaf6);border:1px dashed #b8c5d3;display:grid;place-items:center;overflow:hidden;color:var(--muted);text-align:center;padding:12px}.image img{width:100%;height:100%;object-fit:cover;display:block}
    .tab{border-color:#cfd8e5}.tab.active{background:#182230;border-color:#182230;color:#fff}.mode-tabs{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-bottom:9px}.mode{min-height:34px}.mode.active{background:#182230;border-color:#182230;color:#fff}.suggestions{display:flex;gap:6px;flex-wrap:wrap;margin:2px 0 9px}.suggestion{min-height:30px;padding:0 9px;font-size:12px;border-color:#d2dae6;background:#fff;color:#253044}.status{min-height:20px;color:#475467;font-size:13px;margin-top:8px;border:1px solid #e1e7ee;background:#f8fafc;border-radius:8px;padding:7px 9px}.meta{font-size:12px;color:var(--muted);line-height:1.4;margin-top:8px;word-break:break-word}
    .costs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:0 0 10px}.cost{background:#fff;border:1px solid var(--line);border-top:3px solid var(--accent);border-radius:8px;padding:9px 10px;box-shadow:0 1px 2px rgba(18,24,33,.04)}.cost:nth-child(2){border-top-color:var(--blue)}.cost:nth-child(3){border-top-color:var(--green)}.cost:nth-child(4){border-top-color:var(--amber)}.cost strong{display:block;color:var(--ink);font-size:13px}.cost span{font-size:12px;color:var(--muted)}
    .account{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:end;background:linear-gradient(135deg,#182230 0,#223247 58%,#173c35 100%);color:#fff;border:1px solid #293548;border-radius:8px;padding:11px 12px;margin:0 0 10px;box-shadow:var(--shadow)}.account p,.account label{color:#d6dde7}.account .signed{display:none}.account.authed .signed{display:block}.account.authed .login{display:none}.account input{margin:0;background:#fff}.account strong{display:block;color:#fff}.account .danger{color:var(--danger)}
    .library{display:grid;gap:8px;margin-top:10px;max-height:270px;overflow:auto}.draft-item{border:1px solid var(--line);background:#fff;border-radius:8px;padding:9px;display:grid;gap:8px;box-shadow:0 1px 2px rgba(18,24,33,.04)}.draft-item strong{font-size:13px}.draft-item span{font-size:12px;color:var(--muted)}.draft-item .row{display:flex;gap:6px;flex-wrap:wrap}
    .checklist{display:grid;gap:7px;margin-top:10px;border-top:1px solid #edf1f5;padding-top:10px}.check{display:flex;gap:8px;align-items:flex-start;color:var(--muted);font-size:12px}.check input{width:auto;margin-top:3px}.small{font-size:12px;color:var(--muted)}.score{display:grid;gap:7px;border:1px solid var(--line);background:#fbfcfe;border-radius:8px;padding:10px;margin-top:10px}.score-row{display:flex;align-items:center;justify-content:space-between;gap:10px;font-size:12px;color:#475467}.badge{border:1px solid #d8dee8;border-radius:999px;padding:3px 8px;background:#fff;font-weight:820;color:#667085}.badge.ok{color:#146c43;border-color:#b7e4d3;background:#f3fcf8}.badge.warn{color:#9f2d20;border-color:#f2c7c3;background:#fff7f5}.image-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}.preview-card{border:1px solid var(--line);border-left:3px solid var(--green);border-radius:8px;background:#fbfcfe;padding:11px;margin-top:10px;white-space:pre-wrap;line-height:1.45;font-size:14px;max-height:220px;overflow:auto}
    /* Colorful studio theme: presentation only; account and billing logic are unchanged. */
    :root{--bg:#f5f5fc;--ink:#20223d;--muted:#59617b;--line:#e1e4f2;--accent:#6546d7;--green:#087f78;--blue:#dd7a73;--amber:#ac5c0a;--shadow:0 8px 30px rgba(47,43,105,.065)}
    body{position:relative;overflow-x:hidden;background:linear-gradient(180deg,#f7f8ff 0,#f5f5fc 310px,var(--bg) 100%)}
    body:before{content:"";position:fixed;inset:0;pointer-events:none;background:linear-gradient(180deg,rgba(245,245,252,.02) 0,rgba(245,245,252,.14) 32%,rgba(245,245,252,.76) 72%,#f5f5fc 100%),linear-gradient(90deg,rgba(245,245,252,.04) 0,rgba(245,245,252,.48) 33%,rgba(245,245,252,.5) 67%,rgba(245,245,252,.04) 100%),url('/assets/fun-studio-creator-background.png') center 8%/cover no-repeat}
    body:after{content:"";position:fixed;inset:0;pointer-events:none;background:linear-gradient(90deg,rgba(101,70,215,.18) 0 1px,transparent 1px 88px),linear-gradient(180deg,rgba(8,127,120,.13) 0 1px,transparent 1px 52px);opacity:.28;mask-image:linear-gradient(180deg,#000 0,rgba(0,0,0,.65) 38%,transparent 72%)}
    main{position:relative;z-index:1;padding:24px 0 36px}
    .creative-scene{width:clamp(240px,27vw,440px);flex:none;padding:10px 14px;border:1px solid #ddd4f4;border-radius:18px;background:#ffffff80}.creative-scene svg{display:block;width:100%;height:auto}.creative-scene button{display:flex;margin:4px auto 0;min-height:28px;font-size:11px;padding:0 10px}.draw-line{stroke-dasharray:1;stroke-dashoffset:1;animation:sketch-draw 2s ease forwards}.stage-two{animation-delay:1.8s}.stage-three{animation-delay:3.6s}.stage-four{animation-delay:5.4s}.stage-five{animation-delay:7.2s}.sketch-color{opacity:0;animation:sketch-fill 2s ease 8s forwards}@keyframes sketch-draw{to{stroke-dashoffset:0}}@keyframes sketch-fill{to{opacity:1}}
    @media(max-width:1200px){header{flex-wrap:wrap}.creative-scene{width:280px}}
    @media(max-width:760px){.creative-scene{width:100%;max-width:440px}}
    @media(prefers-reduced-motion:reduce){.draw-line{animation:none;stroke-dashoffset:0}.sketch-color{animation:none;opacity:1}}
    header{position:relative;overflow:hidden;border-color:#dedff4;border-radius:22px;padding:24px;margin-bottom:16px;background:linear-gradient(90deg,rgba(255,255,255,.92) 0,rgba(255,255,255,.72) 34%,rgba(255,255,255,.18) 100%),url('/assets/fun-studio-creator-background.png') center 18%/cover no-repeat;min-height:290px;box-shadow:0 18px 52px rgba(48,39,101,.12)}
    header:before{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(90deg,rgba(255,255,255,.88) 0 32%,rgba(255,255,255,.3) 50%,rgba(255,255,255,.02) 100%),linear-gradient(180deg,rgba(255,255,255,.08),rgba(245,245,252,.24)),radial-gradient(circle at 16% 74%,rgba(255,206,121,.24),transparent 24%);opacity:1}
    header:after{content:"";position:absolute;right:18px;top:18px;width:44%;height:calc(100% - 36px);pointer-events:none;border-radius:18px;background:linear-gradient(135deg,rgba(255,255,255,.2),rgba(255,255,255,.02)),repeating-linear-gradient(90deg,rgba(255,255,255,.26) 0 1px,transparent 1px 34px),repeating-linear-gradient(180deg,rgba(8,127,120,.16) 0 1px,transparent 1px 28px);box-shadow:inset 0 0 0 1px rgba(255,255,255,.38)}
    header>div{position:relative;z-index:1}
    h1{font-size:clamp(30px,4vw,42px);letter-spacing:-1.4px;line-height:1.15;color:#302765}
    .studio-brand{position:relative;display:flex;align-items:center;gap:14px}.studio-brand:before{content:"";position:absolute;left:78px;top:-13px;width:172px;height:9px;border-radius:999px;background:linear-gradient(90deg,#6546d7 0 22%,#5ce0c7 22% 46%,#ffce79 46% 58%,transparent 58%);opacity:.7}.studio-brand:after{content:"";position:absolute;left:82px;bottom:-13px;width:226px;height:24px;border:1px solid rgba(101,70,215,.18);border-radius:999px;background:repeating-linear-gradient(90deg,rgba(101,70,215,.16) 0 8px,transparent 8px 15px),linear-gradient(90deg,rgba(255,255,255,.64),rgba(255,255,255,0));opacity:.78}.creative-mark{width:68px;height:68px;flex:none;filter:drop-shadow(0 5px 9px #6546d71f)}
    @media(max-width:760px){.studio-brand{gap:10px}.creative-mark{width:52px;height:52px}.studio-brand h1{font-size:clamp(24px,7vw,34px)}}
    header p{position:relative;max-width:660px;margin-top:18px;font-size:14px;line-height:1.65}header p:after{content:"";display:block;width:min(420px,80%);height:34px;margin-top:12px;border-radius:13px;background:linear-gradient(90deg,rgba(101,70,215,.1),rgba(8,127,120,.09)),repeating-linear-gradient(90deg,rgba(48,39,101,.13) 0 1px,transparent 1px 26px);border:1px solid rgba(101,70,215,.13)}
    .eyebrow{position:relative;background:#ede8ff;border-color:#d8cef9;color:#5635af;padding:6px 11px;letter-spacing:.02em}.eyebrow:after{content:"";position:absolute;right:-58px;top:50%;width:46px;height:1px;background:linear-gradient(90deg,#c8b8f5,transparent)}
    .creative-scene{position:relative;z-index:1;background:linear-gradient(135deg,rgba(255,255,255,.82),rgba(245,241,255,.72));box-shadow:inset 0 0 0 1px rgba(255,255,255,.72),0 12px 34px rgba(48,39,101,.08)}
    .creative-scene:before{content:"";position:absolute;inset:8px;border-radius:14px;pointer-events:none;background:linear-gradient(90deg,rgba(101,70,215,.13) 0 1px,transparent 1px 32px),linear-gradient(180deg,rgba(8,127,120,.12) 0 1px,transparent 1px 24px);mask-image:radial-gradient(circle at 50% 50%,transparent 0 76px,#000 116px)}
    .creative-scene:after{content:"";position:absolute;left:22px;right:22px;bottom:11px;height:16px;border-radius:999px;pointer-events:none;background:linear-gradient(90deg,rgba(101,70,215,.22),rgba(92,224,199,.24)),repeating-linear-gradient(90deg,rgba(255,255,255,.8) 0 2px,transparent 2px 16px);opacity:.82}
    .hero-detail-board{display:grid;grid-template-columns:92px 1fr 118px;gap:10px;align-items:stretch;width:min(580px,100%);margin-top:16px;opacity:.82}
    .detail-card{position:relative;min-height:70px;border:1px solid rgba(101,70,215,.2);border-radius:16px;background:rgba(255,255,255,.74);box-shadow:0 10px 28px rgba(48,39,101,.08),inset 0 0 0 1px rgba(255,255,255,.7);overflow:hidden}
    .detail-card.media:before{content:"";position:absolute;inset:10px;border-radius:12px;background:linear-gradient(135deg,#7150da,#56d0c2 58%,#ffce79);box-shadow:inset 0 0 0 1px rgba(255,255,255,.45)}
    .detail-card.media:after{content:"";position:absolute;left:35px;top:27px;width:0;height:0;border-top:9px solid transparent;border-bottom:9px solid transparent;border-left:15px solid rgba(255,255,255,.92);filter:drop-shadow(0 2px 5px rgba(48,39,101,.18))}
    .detail-card.timeline{padding:13px 14px;display:grid;gap:8px}
    .detail-card.timeline span{display:block;height:8px;border-radius:999px;background:#e7e3f8}
    .detail-card.timeline span:nth-child(1){width:72%;background:linear-gradient(90deg,#6546d7,#8d75e8)}
    .detail-card.timeline span:nth-child(2){width:92%;background:linear-gradient(90deg,#087f78,#5ce0c7)}
    .detail-card.timeline span:nth-child(3){width:54%;background:linear-gradient(90deg,#ffce79,#f1b4e6)}
    .detail-card.palette{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;padding:10px}
    .detail-card.palette span{border-radius:11px;background:#6546d7;box-shadow:inset 0 0 0 1px rgba(255,255,255,.45)}
    .detail-card.palette span:nth-child(2){background:#087f78}.detail-card.palette span:nth-child(3){background:#ffce79}.detail-card.palette span:nth-child(4){background:#f1b4e6}
    .layout{position:relative;gap:16px}.layout:before{content:"";position:absolute;left:326px;right:360px;top:12px;height:78px;border-radius:18px;pointer-events:none;background:linear-gradient(90deg,rgba(101,70,215,.14),transparent 48%),repeating-linear-gradient(90deg,rgba(8,127,120,.16) 0 12px,transparent 12px 24px);opacity:.75}.layout:after{content:"";position:absolute;left:326px;right:360px;bottom:20px;height:86px;border-radius:18px;pointer-events:none;background:repeating-linear-gradient(90deg,rgba(48,39,101,.08) 0 1px,transparent 1px 34px),linear-gradient(180deg,rgba(255,255,255,.7),rgba(101,70,215,.08));opacity:.75}.panel{position:relative;z-index:1;border-radius:20px;padding:18px;background:#fff}
    .layout>aside:first-child{border-top:4px solid #8561e9}.layout>section{border-top:4px solid #ee8c7c}.layout>.side{border-top:4px solid #25a99d}
    h2{font-size:12px;color:#515673;margin-bottom:14px;letter-spacing:.1em}h2:before{width:8px;height:8px;background:#8964e5;box-shadow:0 0 0 4px #f0ebff}.side h2:before{background:#17968b;box-shadow:0 0 0 4px #e5f7f3}
    button,.button{border-radius:11px;min-height:39px;font-weight:720;transition:background .18s,box-shadow .18s,transform .18s}
    button:not(.secondary),.button:not(.secondary){background:linear-gradient(120deg,#7150da,#5740bd);border-color:#6546d7;box-shadow:0 3px 9px #6546d724}
    button.green{background:linear-gradient(120deg,#09877e,#076c68);border-color:#087f78;box-shadow:0 3px 9px #087f7824}
    button.blue{background:linear-gradient(120deg,#f39a82,#d87372);border-color:#e28a78;box-shadow:0 3px 9px rgba(221,122,115,.18);color:#fff}
    button.secondary:hover,.button.secondary:hover{background:#f4f1ff;border-color:#c5b7ef;box-shadow:0 3px 10px #6546d710}
    button:focus-visible,a:focus-visible{outline:3px solid #9075e5;outline-offset:3px}
    .mode.active,.tab.active{background:#eee8ff!important;border-color:#c7b6f4!important;color:#5430a6!important;box-shadow:none}
    input,select,textarea{border-radius:11px;border-color:#dfe3f0;background:#fcfcff}input:focus,select:focus,textarea:focus{outline:3px solid #7857d91a;border-color:#9f87e4}
    input[type=checkbox]{accent-color:#6546d7}.post{background:linear-gradient(180deg,#fcfcff,#fff);padding:15px;margin-top:12px;line-height:1.7}
    .suggestion{border-radius:999px;min-height:30px;background:#f8f6ff;color:#584684;border-color:#e4dcf7}.suggestion:nth-child(3n){background:#edf8f6;color:#1c6b61;border-color:#d4eeea}
    .account{border-radius:18px;padding:18px 20px;margin-bottom:16px;background:linear-gradient(115deg,#302657,#3f3679 60%,#185c63);border-color:#453b7d}.account p,.account label{color:#e0e3f3}.account strong{font-size:15px}.account .button.secondary,.account button.secondary{background:#fff;color:#302765}
    .costs{gap:12px;margin-bottom:16px}.cost{border-radius:15px;padding:13px 16px;border-top-width:3px}.cost strong{font-size:14px;margin-bottom:4px}.cost:nth-child(1){background:#f1ecff;border-color:#e0d7fa;border-top-color:#8964df}.cost:nth-child(2){background:#fff5f2;border-color:#f7d8ce;border-top-color:#ee8c7c}.cost:nth-child(3){background:#e9f8f4;border-color:#d2eee5;border-top-color:#23998b}.cost:nth-child(4){background:#fff3e6;border-color:#f6e2c9;border-top-color:#df9747}
    .image{border-radius:15px;background:radial-gradient(circle at 20% 20%,#e8ddff,transparent 60%),linear-gradient(135deg,#f1f0ff,#e5f6f2);border-color:#c8c5e4;color:#626181;min-height:160px}
    .preview-card{background:#fff8f5;border-color:#f4ddd5;border-left-color:#ee8c7c;border-radius:13px;padding:15px}.score{background:#f8f7fd;border-color:#e5e0f4;border-radius:13px;padding:13px}.status{background:#f4f1fc;border-color:#e5def5;border-radius:11px;padding:10px 12px}.draft-item{border-radius:13px;background:#fcfbff}.badge{font-size:11px}.checklist{gap:10px;padding-top:14px}.check{line-height:1.5}
    @media(prefers-reduced-motion:reduce){button,.button{transition:none}button:hover,.button:hover{transform:none}}
    @media(max-width:1040px){.layout{grid-template-columns:minmax(0,1fr) minmax(0,1fr)}.layout:before,.layout:after,body:after{display:none}.side{grid-column:1/-1}.costs{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){main{padding-top:12px}header{padding:20px;border-radius:18px;align-items:flex-start;flex-direction:column}.hero-detail-board{grid-template-columns:1fr 1.4fr;width:100%}.detail-card.palette{grid-column:1/-1;grid-template-columns:repeat(4,1fr);min-height:46px}.layout,.two,.account{grid-template-columns:minmax(0,1fr)}.panel{padding:16px}.post{min-height:300px}.image-actions{grid-template-columns:1fr}.costs{grid-template-columns:repeat(2,minmax(0,1fr))}.cost{padding:11px}h1{letter-spacing:-.7px}}
  </style>
</head>
<body>
  <main>
    <header>
      <div><div class="eyebrow">AI workflow za ustvarjalce</div><div class="studio-brand"><svg class="creative-mark" viewBox="0 0 80 80" fill="none" aria-hidden="true" focusable="false"><defs><linearGradient id="creative-bg" x1="5" y1="5" x2="76" y2="80" gradientUnits="userSpaceOnUse"><stop stop-color="#7254df"/><stop offset="1" stop-color="#3c34a5"/></linearGradient><linearGradient id="creative-pencil" x1="25" y1="58" x2="60" y2="24" gradientUnits="userSpaceOnUse"><stop stop-color="#5ce0c7"/><stop offset="1" stop-color="#b9fff0"/></linearGradient></defs><rect x="4" y="4" width="72" height="72" rx="23" fill="url(#creative-bg)"/><path d="M13 52C9 29 35 11 56 17M23 68C48 76 70 53 67 35" stroke="#b6a5f5" stroke-width="1.5" stroke-linecap="round" opacity=".5"/><path d="m25 48 25-25a5 5 0 0 1 7 0l4 4a5 5 0 0 1 0 7L36 59l-15 4 4-15Z" fill="url(#creative-pencil)"/><path d="m49 24 12 12" stroke="#087f78" stroke-width="3"/><path d="m25 48 11 11-15 4 4-15Z" fill="#fff0cb"/><path d="m23 56 5 5-7 2 2-7Z" fill="#343358"/><path d="m31 49 18-18" stroke="white" stroke-width="2.5" stroke-linecap="round" opacity=".85"/><path d="m22 19 2.5 6.5L31 28l-6.5 2.5L22 37l-2.5-6.5L13 28l6.5-2.5L22 19Z" fill="#ffce79"/><path d="m61 47 2 5 5 2-5 2-2 5-2-5-5-2 5-2 2-5Z" fill="#f1b4e6"/><circle cx="42" cy="15" r="2" fill="#f1b4e6"/>${creativeDetails}</svg><h1>Content Studio</h1></div><p>Ustvari, uredi in shrani objave, slike ter video osnutke za družbena omrežja na enem mestu. Objavo vedno pregledaš in objaviš ročno.</p><div class="hero-detail-board" aria-hidden="true"><span class="detail-card media"></span><span class="detail-card timeline"><span></span><span></span><span></span></span><span class="detail-card palette"><span></span><span></span><span></span><span></span></span></div></div>
      <div class="creative-scene" id="creativeScene">${evolvingSketch}</div>
      <div class="actions"><a class="button secondary" href="/admin">Admin</a><a class="button secondary" href="/pricing">Naročnine</a><a class="button secondary" href="/video">Video editor</a></div>
    </header>

    <section class="account" id="accountBox">
      <div class="login">
        <label>E-mail za prijavo<input id="email" type="email" placeholder="tvoj@email.com" /></label>
        <p class="small">Geslo ni potrebno. Vpiši e-mail in prijavo potrdi z enkratno kodo, ki jo prejmeš po e-pošti. Admin koda je samo za skrbnika.</p>
        <label>Admin koda (neobvezno — samo za skrbnika)<input id="ownerCode" type="password" placeholder="Običajni uporabniki pustijo prazno" autocomplete="off" /></label>
        <div id="emailVerification" hidden><label>Enkratna koda iz e-maila<input id="emailCode" type="text" inputmode="numeric" autocomplete="one-time-code" maxlength="10" /></label><button id="verifyEmail" type="button">Potrdi e-mail</button></div>
      </div>
      <div class="signed">
        <strong id="accountName">Nisi prijavljen</strong>
        <p id="creditLine">Krediti se naložijo po prijavi.</p>
        <p id="creditHint">Prijavi se za prikaz porabe.</p>
      </div>
      <div class="actions"><button id="login" type="button">Prijava</button><button id="logout" class="secondary" type="button">Odjava</button><a class="button secondary" href="/pricing">Kupi kredite</a></div>
    </section>

    <section class="costs">
      <div class="cost"><strong>Tekst</strong><span>5 kreditov</span></div>
      <div class="cost"><strong>Izboljšava</strong><span>3 krediti</span></div>
      <div class="cost"><strong>Slika</strong><span>15 kreditov</span></div>
      <div class="cost"><strong>Video</strong><span>25 kreditov</span></div>
    </section>

    <section class="layout">
      <aside class="panel">
        <h2>Pogovor</h2>
        <div class="mode-tabs"><button class="secondary mode active" data-mode="chat" type="button">Pogovor z agentom</button><button class="secondary mode" data-mode="post" type="button">Hitro ustvari objavo</button></div>
        <label>Kaj želiš ustvariti?<input id="topic" placeholder="Npr. predstavi sebe kaj počneš, napiši odgovor, pripravi objavo za FB..." /></label>
        <label>Namen<select id="intent"><option value="auto">Samodejno iz navodila</option><option value="Predstavitev">Predstavitev</option><option value="Mnenje">Mnenje</option><option value="Odgovor na vprašanje">Odgovor na vprašanje</option><option value="Oglas">Oglas</option><option value="Osebna objava">Osebna objava</option><option value="Izobraževalna objava">Izobraževalna objava</option><option value="Provokativna debata">Provokativna debata</option><option value="Prodajna objava">Prodajna objava</option><option value="Zgodba">Zgodba</option><option value="Kratek X post">Kratek X post</option></select></label>
        <label>Ciljna publika<input id="audience" placeholder="Npr. ženske in moški v FB skupini, podjetniki, ustvarjalci, kupci..." /></label>
        <div class="suggestions">
          <button class="suggestion" data-prompt="Predstavi moj projekt za Facebook, Instagram in X. Naj bo jasno, uporabno in človeško." type="button">Predstavi moj projekt</button>
          <button class="suggestion" data-prompt="Napiši FB objavo na temo: " type="button">Napiši FB objavo</button>
          <button class="suggestion" data-prompt="Napiši odgovor na to vprašanje: " type="button">Napiši odgovor</button>
          <button class="suggestion" data-prompt="Naredi ta tekst bolj človeški, manj AI in bolj uporaben: " type="button">Bolj človeško</button>
          <button class="suggestion" data-prompt="Naredi ta tekst bolj prodajen, ampak ne vsiljiv: " type="button">Bolj prodajno</button>
          <button class="suggestion" data-prompt="Naredi ta tekst krajši in močnejši: " type="button">Naredi krajše</button>
        </div>
        <div class="two">
          <label>Jezik<select id="language"><option value="si">SI</option><option value="eng">ENG</option><option value="esp">ESP</option></select></label>
          <label>Dolžina<select id="length"><option value="medium">Srednja</option><option value="short">Kratka</option><option value="long">Daljša</option></select></label>
        </div>
        <label>Ton<select id="tone"><option value="my-style">Moj slog</option><option value="balanced">Topel + direkten</option><option value="deep">Globok</option><option value="sharp">Bolj oster</option><option value="soft">Nežen</option><option value="story">Kot zgodba</option></select></label>
        <label>Slog slike<select id="imageStyle"><option value="social-editorial">Social editorial</option><option value="artwork-cover">Artwork cover</option><option value="contradictory-art">Kontradiktorni art</option></select></label>
        <label>Kontekst in dodatna navodila<textarea id="notes" class="prompt" placeholder="Piši kot v pogovoru: komu je namenjeno, kaj želiš doseči, kaj naj izpusti, kakšen slog želiš..."></textarea></label>
        <div class="tools"><button id="generateText" class="green" type="button">Pripravi osnutek</button><button id="clear" class="secondary" type="button">Počisti</button></div>
        <div class="status" id="status">Pripravljeno.</div>
        <h2 style="margin-top:16px">Knjižnica</h2>
        <div class="library" id="library"></div>
      </aside>

      <section class="panel">
        <h2>Objava</h2>
        <div class="tabs"><button class="secondary tab active" data-channel="facebook">Facebook</button><button class="secondary tab" data-channel="instagram">Instagram</button><button class="secondary tab" data-channel="x">X</button></div>
        <textarea id="postText" class="post" spellcheck="true" placeholder="Najprej napiši, kaj želiš, nato klikni Pripravi osnutek."></textarea>
        <div class="tools">
          <button id="copyText" class="secondary" type="button">Kopiraj</button>
          <button id="saveDraft" class="secondary" type="button">Shrani</button>
          <button class="secondary refine" data-action="my-style" type="button">Moj slog</button>
          <button class="secondary refine" data-action="sharper" type="button">Bolj ostro</button>
          <button class="secondary refine" data-action="emotional" type="button">Bolj čustveno</button>
          <button class="secondary refine" data-action="less-ai" type="button">Manj AI</button>
          <button class="secondary refine" data-action="shorter" type="button">Krajše</button>
          <button class="secondary refine" data-action="longer" type="button">Daljše</button>
          <button class="secondary refine" data-action="question" type="button">Boljši konec</button>
        </div>
        <div class="preview-card" id="previewCard">Predogled objave bo tukaj.</div>
        <div class="score" id="scoreBox">
          <div class="score-row"><span>Drži se navodila</span><span class="badge" id="scoreInstruction">-</span></div>
          <div class="score-row"><span>Uporabno za objavo</span><span class="badge" id="scoreUseful">-</span></div>
          <div class="score-row"><span>Zveni preveč AI</span><span class="badge" id="scoreAi">-</span></div>
          <button id="autoFix" class="secondary" type="button">Popravi samodejno</button>
        </div>
        <div class="checklist">
          <label class="check"><input type="checkbox" /> Tekst sem prebral in zveni kot jaz.</label>
          <label class="check"><input type="checkbox" /> Slika ustreza temi in ni zavajajoča.</label>
          <label class="check"><input type="checkbox" /> Objavljam ročno, nič ni bilo poslano samo.</label>
        </div>
      </section>

      <aside class="panel side">
        <h2>Slika in video</h2>
        <div class="image" id="imageBox">Slika bo tukaj šele, ko klikneš Generiraj sliko.</div>
        <div class="image-actions"><button id="generateImage" class="green" type="button">Generiraj sliko</button><button id="downloadImage" class="secondary" type="button">Prenesi sliko</button></div>
        <div class="image-actions"><button id="copyImage" class="secondary" type="button">Kopiraj sliko</button><button id="sendToVideo" class="blue" type="button">Ustvari video</button></div>
        <div class="meta" id="imageMeta"></div>
        <h2 style="margin-top:16px">Video opis</h2>
        <textarea id="videoPrompt" class="prompt" placeholder="Opis za premik slike v video."></textarea>
        <p class="small">Video porablja Runway kredite. Uporabi ga šele, ko sta tekst in slika dobra.</p>
        <p class="small">AI video se odklene po potrjenem nakupu kreditov. Začetnih 50 brezplačnih kreditov ga ne odklene. Lokalni WebM izvoz ostane brezplačen.</p>
      </aside>
    </section>
  </main>
  <script>
    const uiTranslations = [
      ["Geslo ni potrebno. Vpiši e-mail in prijavo potrdi z enkratno kodo, ki jo prejmeš po e-pošti. Admin koda je samo za skrbnika.","No password is required. Enter your email and confirm sign-in with the one-time code sent to your inbox. The admin code is for administrators only.","No necesitas contraseña. Introduce tu correo y confirma el acceso con el código de un solo uso que recibirás por correo. El código de administrador es solo para administradores."],
      ["Enkratna koda iz e-maila","One-time email code","Código de un solo uso del correo"],
      ["Potrdi e-mail","Verify email","Verificar correo"],
      ["Preverjam kodo...","Verifying code...","Verificando código..."],
      ["Koda je poslana. Preveri e-mail in vpiši prejeto kodo.","Code sent. Check your inbox and enter the code.","Código enviado. Revisa tu correo e introduce el código."],
      ["Ponovi izris","Replay drawing","Repetir dibujo"],
      ["Za običajno prijavo zadostuje e-mail. Geslo ni potrebno; admin kodo pusti prazno.","For a regular sign-in, enter only your email. No password is required; leave the admin code empty.","Para iniciar sesión como usuario, introduce solo tu correo. No necesitas contraseña; deja vacío el código de administrador."],
      ["Admin koda (neobvezno — samo za skrbnika)","Admin code (optional — administrators only)","Código de administrador (opcional — solo administradores)"],
      ["Običajni uporabniki pustijo prazno","Regular users leave this empty","Los usuarios dejan este campo vacío"],
      ["AI video se odklene po potrjenem nakupu kreditov. Začetnih 50 brezplačnih kreditov ga ne odklene. Lokalni WebM izvoz ostane brezplačen.","AI video requires a confirmed credit purchase. The free 50 credits do not unlock it. Local WebM export remains free.","El vídeo con IA requiere una compra de créditos confirmada. Los 50 créditos gratuitos no lo desbloquean. La exportación WebM local sigue siendo gratuita."],
      ["AI workflow za ustvarjalce","AI workflow for creators","Flujo de IA para creadores"],
      ["Ustvari, uredi in shrani objave, slike ter video osnutke za družbena omrežja na enem mestu. Objavo vedno pregledaš in objaviš ročno.","Create, edit and save social posts, images and video drafts in one place. Always review and publish manually.","Crea, edita y guarda publicaciones, imágenes y borradores de vídeo en un solo lugar. Revisa y publica siempre manualmente."],
      ["Admin","Admin","Administración"],["Naročnine","Subscriptions","Suscripciones"],["Video editor","Video editor","Editor de vídeo"],
      ["E-mail za prijavo","Login email","Correo de acceso"],["Admin koda","Admin code","Código de administrador"],["Samo za lastnika","Owner only","Solo para el propietario"],["Nisi prijavljen","Not signed in","No has iniciado sesión"],
      ["Krediti se naložijo po prijavi.","Credits load after sign-in.","Los créditos se cargan al iniciar sesión."],["Prijavi se za prikaz porabe.","Sign in to view usage.","Inicia sesión para ver el consumo."],
      ["Prijava","Sign in","Iniciar sesión"],["Odjava","Sign out","Cerrar sesión"],["Kupi kredite","Buy credits","Comprar créditos"],
      ["Tekst","Text","Texto"],["Izboljšava","Refinement","Mejora"],["Slika","Image","Imagen"],["Video","Video","Vídeo"],
      ["5 kreditov","5 credits","5 créditos"],["3 krediti","3 credits","3 créditos"],["15 kreditov","15 credits","15 créditos"],["25 kreditov","25 credits","25 créditos"],
      ["Pogovor","Conversation","Conversación"],["Pogovor z agentom","Chat with the agent","Conversar con el agente"],["Hitro ustvari objavo","Quick post","Publicación rápida"],
      ["Kaj želiš ustvariti?","What would you like to create?","¿Qué quieres crear?"],["Namen","Purpose","Objetivo"],["Samodejno iz navodila","Automatic from instructions","Automático según las instrucciones"],
      ["Predstavitev","Introduction","Presentación"],["Mnenje","Opinion","Opinión"],["Odgovor na vprašanje","Answer a question","Respuesta a una pregunta"],["Oglas","Advertisement","Anuncio"],["Osebna objava","Personal post","Publicación personal"],["Izobraževalna objava","Educational post","Publicación educativa"],["Provokativna debata","Provocative discussion","Debate provocador"],["Prodajna objava","Sales post","Publicación de ventas"],["Zgodba","Story","Historia"],["Kratek X post","Short X post","Publicación corta en X"],
      ["Ciljna publika","Target audience","Público objetivo"],["Predstavi moj projekt","Introduce my project","Presentar mi proyecto"],["Napiši FB objavo","Write a Facebook post","Escribir una publicación de Facebook"],["Napiši odgovor","Write a reply","Escribir una respuesta"],["Bolj človeško","More human","Más humano"],["Bolj prodajno","More persuasive","Más persuasivo"],["Naredi krajše","Make it shorter","Hacerlo más corto"],
      ["Jezik","Language","Idioma"],["Dolžina","Length","Longitud"],["Srednja","Medium","Media"],["Kratka","Short","Corta"],["Daljša","Long","Larga"],["Ton","Tone","Tono"],["Moj slog","My style","Mi estilo"],["Topel + direkten","Warm + direct","Cálido + directo"],["Globok","Deep","Profundo"],["Bolj oster","Sharper","Más contundente"],["Nežen","Gentle","Suave"],["Kot zgodba","Storytelling","Narrativo"],
      ["Slog slike","Image style","Estilo de imagen"],["Social editorial","Social editorial","Editorial para redes"],["Artwork cover","Artwork cover","Portada artística"],["Kontradiktorni art","Contrasting art","Arte de contraste"],
      ["Kontekst in dodatna navodila","Context and additional instructions","Contexto e instrucciones adicionales"],["Pripravi osnutek","Create draft","Crear borrador"],["Počisti","Clear","Limpiar"],["Pripravljeno.","Ready.","Listo."],["Knjižnica","Library","Biblioteca"],["Objava","Post","Publicación"],
      ["Kopiraj","Copy","Copiar"],["Shrani","Save","Guardar"],["Bolj ostro","Sharper","Más contundente"],["Bolj čustveno","More emotional","Más emotivo"],["Manj AI","Less AI","Menos IA"],["Krajše","Shorter","Más corto"],["Daljše","Longer","Más largo"],["Boljši konec","Better ending","Mejor cierre"],
      ["Predogled objave bo tukaj.","Your post preview will appear here.","La vista previa aparecerá aquí."],["Drži se navodila","Follows instructions","Sigue las instrucciones"],["Uporabno za objavo","Ready to post","Útil para publicar"],["Zveni preveč AI","Sounds too AI-generated","Suena demasiado artificial"],["Popravi samodejno","Fix automatically","Corregir automáticamente"],["Da","Yes","Sí"],["Ne","No","No"],
      ["Tekst sem prebral in zveni kot jaz.","I have read the text and it sounds like me.","He leído el texto y suena como yo."],["Slika ustreza temi in ni zavajajoča.","The image fits the topic and is not misleading.","La imagen corresponde al tema y no es engañosa."],["Objavljam ročno, nič ni bilo poslano samo.","I publish manually; nothing was sent automatically.","Publico manualmente; nada se ha enviado automáticamente."],
      ["Slika in video","Image and video","Imagen y vídeo"],["Slika bo tukaj šele, ko klikneš Generiraj sliko.","Click Generate image to create an image here.","Pulsa Generar imagen para crear una imagen aquí."],["Generiraj sliko","Generate image","Generar imagen"],["Prenesi sliko","Download image","Descargar imagen"],["Kopiraj sliko","Copy image","Copiar imagen"],["Ustvari video","Create video","Crear vídeo"],["Video opis","Video description","Descripción del vídeo"],["Opis za premik slike v video.","Describe how the image should move in the video.","Describe cómo debe moverse la imagen en el vídeo."],
      ["Video porablja Runway kredite. Uporabi ga šele, ko sta tekst in slika dobra.","Video uses Runway credits. Use it once the text and image are ready.","El vídeo consume créditos de Runway. Úsalo cuando el texto y la imagen estén listos."],
      ["Npr. predstavi sebe kaj počneš, napiši odgovor, pripravi objavo za FB...","E.g. introduce yourself, write a reply, prepare a Facebook post...","Por ejemplo: preséntate, escribe una respuesta o prepara una publicación..."],["Npr. ponos, izdaja, prevara, denar...","E.g. pride, betrayal, scams, money...","Por ejemplo: orgullo, traición, estafas, dinero..."],["Npr. ženske in moški v FB skupini, podjetniki, ustvarjalci, kupci...","E.g. a Facebook group, entrepreneurs, creators, customers...","Por ejemplo: un grupo de Facebook, emprendedores, creadores, clientes..."],
      ["Piši kot v pogovoru: komu je namenjeno, kaj želiš doseči, kaj naj izpusti, kakšen slog želiš...","Describe the audience, your goal, what to omit and the style you want...","Describe el público, tu objetivo, qué omitir y el estilo que quieres..."],["Najprej napiši, kaj želiš, nato klikni Pripravi osnutek.","Describe what you want, then click Create draft.","Describe lo que quieres y pulsa Crear borrador."],
      ["Shranjeni osnutki bodo tukaj.","Saved drafts will appear here.","Los borradores guardados aparecerán aquí."],["Odpri","Open","Abrir"],["Izbriši","Delete","Eliminar"],["Osnutek","Draft","Borrador"],
      ["Admin račun: neomejena uporaba.","Admin account: unlimited usage.","Cuenta de administrador: uso ilimitado."],["Upravljaš lahko uporabnike, kredite in sredstva v adminu.","Manage users, credits and funds in Admin.","Gestiona usuarios, créditos y fondos en Administración."],
      ["Razmišljam...","Thinking...","Pensando..."],["Pišem...","Writing...","Escribiendo..."],["Generiram...","Generating...","Generando..."],["Generiram sliko...","Generating image...","Generando imagen..."],["Pripravljam osnutek iz tvojega navodila...","Preparing your draft...","Preparando tu borrador..."],
      ["Osnutek pripravljen. Porabljenih 5 kreditov.","Draft ready. 5 credits used.","Borrador listo. Se han usado 5 créditos."],["Tekst izboljšan. Porabljeni 3 krediti.","Text refined. 3 credits used.","Texto mejorado. Se han usado 3 créditos."],["Slika pripravljena. Porabljenih 15 kreditov.","Image ready. 15 credits used.","Imagen lista. Se han usado 15 créditos."],
      ["Vpiši e-mail.","Enter your email.","Introduce tu correo."],["Prijavljen kot admin.","Signed in as admin.","Sesión de administrador iniciada."],["Prijavljen. Krediti so pripravljeni.","Signed in. Credits are ready.","Sesión iniciada. Créditos disponibles."],["Odjavljen.","Signed out.","Sesión cerrada."],
      ["Najprej generiraj ali vpiši tekst.","Generate or enter text first.","Primero genera o introduce texto."],["Najprej pripravi tekst.","Prepare the text first.","Primero prepara el texto."],["Slika še ni generirana.","No image generated yet.","Todavía no se ha generado una imagen."],["Generirana slika","Generated image","Imagen generada"],["Osnutek odprt.","Draft opened.","Borrador abierto."],["Osnutek shranjen v račun.","Draft saved to your account.","Borrador guardado en tu cuenta."],["Osnutek shranjen lokalno.","Draft saved locally.","Borrador guardado localmente."],["Ni teksta za shranjevanje.","No text to save.","No hay texto para guardar."],["Počiščeno.","Cleared.","Limpiado."],["Tekst kopiran.","Text copied.","Texto copiado."],["Ni slike za kopiranje.","No image to copy.","No hay imagen para copiar."],["Slika kopirana.","Image copied.","Imagen copiada."],["Ni slike za prenos.","No image to download.","No hay imagen para descargar."],["Prenos slike pripravljen.","Image download ready.","Descarga de imagen lista."],["Način: hitro ustvari objavo.","Mode: quick post.","Modo: publicación rápida."],["Način: pogovor z agentom.","Mode: chat with the agent.","Modo: conversar con el agente."]
    ];
    let uiLanguage="si";
    const uiSources=new WeakMap(),uiAttributes=new WeakMap();
    function translate(value){const row=uiTranslations.find((entry)=>entry[0]===value);return row?row[uiLanguage==="eng"?1:uiLanguage==="esp"?2:0]:value}
    function translateInterface(){
      const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;
      while(node=walker.nextNode()){
        const parent=node.parentElement;
        if(!parent||parent.closest("script,style,textarea,#accountName,#imageMeta,.draft-item strong,.draft-item span"))continue;
        const current=node.textContent.trim(),previous=uiSources.get(node);
        if(parent.closest("#previewCard")&&!uiTranslations.find((row)=>row[0]==="Predogled objave bo tukaj.").includes(current))continue;
        const source=previous&&current===previous.translated?previous.source:(uiTranslations.find((row)=>row.includes(current))?.[0]||current);
        const translated=translate(source);uiSources.set(node,{source,translated});
        if(current!==translated)node.textContent=node.textContent.replace(current,translated);
      }
      document.querySelectorAll("[placeholder]").forEach((element)=>{const current=element.getAttribute("placeholder"),previous=uiAttributes.get(element);const source=previous&&current===previous.translated?previous.source:current;const translated=translate(source);uiAttributes.set(element,{source,translated});if(current!==translated)element.setAttribute("placeholder",translated)});
    }
    function applyLanguage(){uiLanguage=language.value;document.documentElement.lang=uiLanguage==="eng"?"en":uiLanguage==="esp"?"es":"sl";localStorage.setItem("zg_studio_language",uiLanguage);renderAccount();translateInterface();const url=new URL(location.href);url.searchParams.set("lang",document.documentElement.lang);history.replaceState(null,"",url)}
    let draft=null,activeChannel="facebook",session=null,inputMode="chat",videoAccess=false;
    const topic=document.getElementById("topic"),intent=document.getElementById("intent"),audience=document.getElementById("audience"),language=document.getElementById("language"),tone=document.getElementById("tone"),length=document.getElementById("length"),imageStyle=document.getElementById("imageStyle"),notes=document.getElementById("notes"),status=document.getElementById("status"),postText=document.getElementById("postText"),imageBox=document.getElementById("imageBox"),imageMeta=document.getElementById("imageMeta"),videoPrompt=document.getElementById("videoPrompt"),previewCard=document.getElementById("previewCard"),library=document.getElementById("library"),accountBox=document.getElementById("accountBox"),accountName=document.getElementById("accountName"),creditLine=document.getElementById("creditLine"),creditHint=document.getElementById("creditHint"),email=document.getElementById("email"),ownerCode=document.getElementById("ownerCode"),scoreInstruction=document.getElementById("scoreInstruction"),scoreUseful=document.getElementById("scoreUseful"),scoreAi=document.getElementById("scoreAi");
    const savedDrafts=JSON.parse(localStorage.getItem("zg_drafts")||"[]");
    function setStatus(v){status.textContent=translate(v)}
    function renderAccount(){
      accountBox.classList.toggle("authed",!!session);accountName.textContent=session?session.email:translate("Nisi prijavljen");
      if(!session){creditLine.textContent=translate("Krediti se naložijo po prijavi.");creditHint.textContent=translate("Prijavi se za prikaz porabe.");return}
      if(session.role==="owner"){creditLine.textContent=translate("Admin račun: neomejena uporaba.");creditHint.textContent=translate("Upravljaš lahko uporabnike, kredite in sredstva v adminu.");return}
      const credits=Number(session.credits||0),costs=session.costs||{text:5,image:15,video:25};
      const texts=Math.floor(credits/costs.text),images=Math.floor(credits/costs.image),videos=Math.floor(credits/costs.video);
      const locale=uiLanguage==="eng"?"en-US":uiLanguage==="esp"?"es-ES":"sl-SI";
      creditLine.textContent=uiLanguage==="eng"?"Available: "+credits.toLocaleString(locale)+" credits.":uiLanguage==="esp"?"Disponibles: "+credits.toLocaleString(locale)+" créditos.":"Na voljo: "+credits.toLocaleString(locale)+" kreditov.";
      const base=uiLanguage==="eng"?"Enough for approximately "+texts+" texts or "+images+" images.":uiLanguage==="esp"?"Suficientes para aproximadamente "+texts+" textos o "+images+" imágenes.":"Dovolj približno za "+texts+" tekstov ali "+images+" slik.";
      const video=videoAccess?(uiLanguage==="eng"?" AI video unlocked: up to "+videos+" five-second videos.":uiLanguage==="esp"?" Vídeo con IA desbloqueado: hasta "+videos+" vídeos de cinco segundos.":" AI video je odklenjen: do "+videos+" petsekundnih videov."):(uiLanguage==="eng"?" AI video is not included in the free version. Unlock it with a confirmed credit purchase.":uiLanguage==="esp"?" La versión gratuita no incluye vídeo con IA. Se desbloquea con una compra de créditos confirmada.":" Brezplačna različica ne omogoča AI videa. Odklene se po potrjenem nakupu kreditov.");
      creditHint.textContent=base+video;
    }
    async function refreshSession(){const response=await fetch("/auth/status");const data=await response.json();session=data.session;videoAccess=data.videoAccess===true;renderAccount();await loadAccountDrafts()}
    async function login(){const value=email.value.trim();if(!value)return setStatus("Vpiši e-mail.");const button=document.getElementById("login");button.disabled=true;try{const response=await fetch("/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:value,ownerCode:ownerCode.value})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"Login failed");if(data.verificationRequired){document.getElementById("emailVerification").hidden=false;document.getElementById("emailCode").value="";document.getElementById("emailCode").focus();setStatus("Koda je poslana. Preveri e-mail in vpiši prejeto kodo.");return}session=data.session;videoAccess=false;renderAccount();await refreshSession();setStatus(session.role==="owner"?"Prijavljen kot admin.":"Prijavljen. Krediti so pripravljeni.")}finally{button.disabled=false}}
    async function verifyEmail(){const button=document.getElementById("verifyEmail");button.disabled=true;setStatus("Preverjam kodo...");try{const response=await fetch("/auth/verify-email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email.value.trim(),code:document.getElementById("emailCode").value.trim()})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"Verification failed");session=data.session;document.getElementById("emailVerification").hidden=true;document.getElementById("emailCode").value="";await refreshSession();setStatus("Prijavljen. Krediti so pripravljeni.")}finally{button.disabled=false}}
    async function logout(){await fetch("/auth/logout",{method:"POST"});session=null;videoAccess=false;renderAccount();setStatus("Odjavljen.")}
    function updateSession(data){if(data&&data.session){session=data.session;renderAccount()}}
    function topicValue(){const mode=inputMode==="post"?"Način: Hitro ustvari objavo. Uporabnik je verjetno vpisal temo, iz nje pripravi uporabno objavo.":"Način: Pogovor z agentom. Uporabnik piše navodilo ali vprašanje, najprej razumi namen in šele potem pripravi osnutek.";const selectedIntent=intent.value&&intent.value!=="auto"?"Namen objave: "+intent.value+"; to je obvezni okvir, ne ugibaj drugega namena.":"";const target=audience.value.trim()?"Ciljna publika: "+audience.value.trim()+". Piši za te ljudi.":"";return [mode,selectedIntent,target,topic.value.trim(),notes.value.trim()].filter(Boolean).join("\\n\\nDodatno: ")}
    function currentText(){return postText.value.trim()}
    function setBusy(button,busy,label){button.disabled=busy;if(label)button.textContent=busy?label:button.dataset.label}
    function channelText(){return draft?.channels?.[activeChannel]?.text||currentText()}
    function setBadge(el,ok,yesText="Da",noText="Ne"){el.textContent=ok?yesText:noText;el.className="badge "+(ok?"ok":"warn")}
    function importantWords(){return (topic.value+" "+notes.value+" "+audience.value).toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g,"").replace(/[^a-z0-9čšžćđ\\s]/gi," ").split(/\\s+/).filter((word)=>word.length>=5&&!["napisi","naredi","pripravi","objavo","odgovor","projekt","facebook","instagram","ustvari","zelim","kako","tema","namen","ciljna","publika"].includes(word)).slice(0,8)}
    function evaluateDraft(){const text=currentText();if(!text){scoreInstruction.textContent="-";scoreUseful.textContent="-";scoreAi.textContent="-";scoreInstruction.className=scoreUseful.className=scoreAi.className="badge";return}const normalized=text.toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g,"");const words=importantWords();const hits=words.filter((word)=>normalized.includes(word)).length;const follows=!words.length||hits>=Math.min(2,words.length);const useful=text.length>=180&&/[.!?]/.test(text)&&!/Tukaj bo|Lorem/i.test(text);const ai=/(v današnjem svetu|pomembno je|vsak ima svojo pot|komunikacija je ključ|globok strah|pod površjem|ta vprašanja niso enostavna|kot umetna inteligenca|ne morem)/i.test(text);setBadge(scoreInstruction,follows);setBadge(scoreUseful,useful);setBadge(scoreAi,!ai,"Ne","Da")}
    function renderPreview(){previewCard.textContent=channelText()||"Predogled objave bo tukaj.";evaluateDraft()}
    function renderDraft(){if(!draft)return;postText.value=channelText();videoPrompt.value=draft.image?.prompt||draft.source?.post||postText.value;renderPreview();if(draft.image?.dataUrl){imageBox.innerHTML="";const img=document.createElement("img");img.src=draft.image.dataUrl;img.alt="Generirana slika";imageBox.appendChild(img);imageMeta.textContent=draft.image.filename||"Generirana slika"}else{imageBox.textContent="Slika še ni generirana.";imageMeta.textContent=""}}
    function saveLibrary(){localStorage.setItem("zg_drafts",JSON.stringify(savedDrafts.slice(0,20)));renderLibrary()}
    async function loadAccountDrafts(){if(!session||session.role==="owner")return;try{const response=await fetch("/drafts/list");const data=await response.json();if(response.ok&&data.ok&&Array.isArray(data.drafts)){savedDrafts.splice(0,savedDrafts.length,...data.drafts.map((item)=>({id:item.id,email:session.email,topic:item.topic,title:item.title,text:item.text,draft:item.draft,createdAt:item.createdAt})));saveLibrary()}}catch{}}
    function renderLibrary(){library.innerHTML="";if(!savedDrafts.length){library.innerHTML='<p class="small">Shranjeni osnutki bodo tukaj.</p>';return}savedDrafts.forEach((item,index)=>{const row=document.createElement("div");row.className="draft-item";row.innerHTML='<strong></strong><span></span><div class="row"><button class="secondary" type="button">Odpri</button><button class="secondary" type="button">Izbriši</button></div>';row.querySelector("strong").textContent=item.title||item.topic||"Osnutek";row.querySelector("span").textContent=(item.text||"").slice(0,120);const buttons=row.querySelectorAll("button");buttons[0].addEventListener("click",()=>{topic.value=item.topic||"";postText.value=item.text||"";draft=item.draft||null;renderPreview();setStatus("Osnutek odprt.")});buttons[1].addEventListener("click",async()=>{buttons[1].disabled=true;try{if(item.id){if(!session||item.email!==session.email)throw new Error("Sign in to the account that owns this draft.");const response=await fetch("/api/auth?action=drafts-delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"Delete failed")}const position=savedDrafts.indexOf(item);if(position>=0)savedDrafts.splice(position,1);saveLibrary()}catch(error){setStatus(error.message);buttons[1].disabled=false}});library.appendChild(row)})}
    async function generateText(){const button=document.getElementById("generateText");button.dataset.label=button.textContent;setBusy(button,true,"Razmišljam...");setStatus("Pripravljam osnutek iz tvojega navodila...");try{const response=await fetch("/agent/draft",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:topicValue(),language:language.value,tone:tone.value,length:length.value,imageStyle:imageStyle.value,includeImage:false})});const data=await response.json();updateSession(data);if(!response.ok||!data.ok)throw new Error(data.error||"Draft failed");draft=data.draft;renderDraft();setStatus("Osnutek pripravljen. Porabljenih 5 kreditov.")}catch(error){setStatus(error instanceof Error?error.message:String(error))}finally{setBusy(button,false)}}
    async function refine(action,button){if(!currentText())return setStatus("Najprej generiraj ali vpiši tekst.");button.dataset.label=button.textContent;setBusy(button,true,"Pišem...");try{const response=await fetch("/agent/rewrite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:draft?.source?.title||topic.value,post:currentText(),hashtags:draft?.source?.hashtags||[],action,language:language.value})});const data=await response.json();updateSession(data);if(!response.ok||!data.ok)throw new Error(data.error||"Rewrite failed");draft={...(draft||{}),source:data.post,channels:{facebook:{title:data.post.title,text:data.post.post+"\\n\\n"+data.post.hashtags.join(" ")},instagram:{title:data.post.title,text:data.post.post+"\\n\\n"+data.post.hashtags.join(" ")},x:{title:data.post.title,text:(data.post.post+" "+data.post.hashtags.slice(0,2).join(" ")).slice(0,280)}}};renderDraft();setStatus("Tekst izboljšan. Porabljeni 3 krediti.")}catch(error){setStatus(error instanceof Error?error.message:String(error))}finally{setBusy(button,false)}}
    async function generateImage(){if(!currentText())return setStatus("Najprej pripravi tekst.");const button=document.getElementById("generateImage");button.dataset.label=button.textContent;setBusy(button,true,"Generiram...");setStatus("Generiram sliko...");try{const response=await fetch("/agent/image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:draft?.source?.title||topic.value||"Objava",post:currentText(),hashtags:draft?.source?.hashtags||[],imageStyle:imageStyle.value})});const data=await response.json();updateSession(data);if(!response.ok||!data.ok)throw new Error(data.error||"Image failed");draft={...(draft||{}),image:data.image};renderDraft();setStatus("Slika pripravljena. Porabljenih 15 kreditov.")}catch(error){setStatus(error instanceof Error?error.message:String(error))}finally{setBusy(button,false)}}
    document.querySelectorAll(".tab").forEach((button)=>button.addEventListener("click",()=>{activeChannel=button.dataset.channel;document.querySelectorAll(".tab").forEach((item)=>item.classList.remove("active"));button.classList.add("active");renderDraft()}));
    document.querySelectorAll(".refine").forEach((button)=>button.addEventListener("click",()=>refine(button.dataset.action,button)));
    document.querySelectorAll(".mode").forEach((button)=>button.addEventListener("click",()=>{inputMode=button.dataset.mode;document.querySelectorAll(".mode").forEach((item)=>item.classList.remove("active"));button.classList.add("active");topic.placeholder=inputMode==="post"?"Npr. ponos, izdaja, prevara, denar...":"Npr. predstavi sebe kaj počneš, napiši odgovor, pripravi objavo za FB...";setStatus(inputMode==="post"?"Način: hitro ustvari objavo.":"Način: pogovor z agentom.")}));
    document.querySelectorAll(".suggestion").forEach((button)=>button.addEventListener("click",()=>{const value=button.dataset.prompt||"";topic.value=topic.value?value+topic.value:value;topic.focus()}));
    document.getElementById("generateText").addEventListener("click",generateText);document.getElementById("generateImage").addEventListener("click",generateImage);
    document.getElementById("autoFix").addEventListener("click",()=>refine("auto-fix",document.getElementById("autoFix")));
    document.getElementById("login").addEventListener("click",()=>login().catch((error)=>setStatus(error instanceof Error?error.message:String(error))));
    document.getElementById("verifyEmail").addEventListener("click",()=>verifyEmail().catch((error)=>setStatus(error instanceof Error?error.message:String(error))));
    document.getElementById("logout").addEventListener("click",()=>logout().catch((error)=>setStatus(error instanceof Error?error.message:String(error))));
    document.getElementById("saveDraft").addEventListener("click",async()=>{const text=currentText();if(!text)return setStatus("Ni teksta za shranjevanje.");const item={topic:topic.value.trim(),title:draft?.source?.title||topic.value.trim(),text,draft,createdAt:new Date().toISOString()};savedDrafts.unshift(item);saveLibrary();try{if(session&&session.role!=="owner"){const response=await fetch("/drafts/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item)});const data=await response.json();if(!response.ok||!data.ok||!data.draft?.id)throw new Error(data.error||"Save failed");Object.assign(item,{id:data.draft.id,email:session.email});saveLibrary();setStatus("Osnutek shranjen v račun.")}else{setStatus("Osnutek shranjen lokalno.")}}catch(error){setStatus("Osnutek je shranjen lokalno. Baza se ni shranila: "+(error instanceof Error?error.message:String(error)))}})
    document.getElementById("clear").addEventListener("click",()=>{topic.value="";notes.value="";audience.value="";intent.value="auto";postText.value="";videoPrompt.value="";imageBox.textContent="Slika bo tukaj šele, ko klikneš Generiraj sliko.";imageMeta.textContent="";draft=null;renderPreview();setStatus("Počiščeno.")});
    document.getElementById("copyText").addEventListener("click",async()=>{await navigator.clipboard.writeText(currentText());setStatus("Tekst kopiran.")});
    document.getElementById("copyImage").addEventListener("click",async()=>{if(!draft?.image?.dataUrl)return setStatus("Ni slike za kopiranje.");const blob=await fetch(draft.image.dataUrl).then((response)=>response.blob());await navigator.clipboard.write([new ClipboardItem({[blob.type]:blob})]);setStatus("Slika kopirana.")});
    document.getElementById("downloadImage").addEventListener("click",()=>{if(!draft?.image?.dataUrl)return setStatus("Ni slike za prenos.");const a=document.createElement("a");a.href=draft.image.dataUrl;a.download=draft.image.filename||"content-studio-image.png";a.click();setStatus("Prenos slike pripravljen.")});
    document.getElementById("sendToVideo").addEventListener("click",()=>{try{sessionStorage.setItem("zg_video_image",draft?.image?.dataUrl||"")}catch{setStatus("Image transfer failed. Download the image and upload it in the video editor.");return}const params=new URLSearchParams({topic:topic.value.trim(),text:currentText().slice(0,1000),language:language.value,from:"studio"});window.location.href="/video?"+params.toString()});
    postText.addEventListener("input",renderPreview);topic.addEventListener("input",evaluateDraft);notes.addEventListener("input",evaluateDraft);audience.addEventListener("input",evaluateDraft);intent.addEventListener("change",evaluateDraft);renderLibrary();renderPreview();
    const requestedLanguage=new URLSearchParams(location.search).get("lang")||localStorage.getItem("zg_studio_language")||"si";
    language.value=({sl:"si",en:"eng",es:"esp",si:"si",eng:"eng",esp:"esp"})[requestedLanguage]||"si";
    language.addEventListener("change",applyLanguage);applyLanguage();
    new MutationObserver(translateInterface).observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:["placeholder"]});
    refreshSession().catch(()=>renderAccount());
  </script>
</body>
</html>`;
}

export default function handler(req: any, res: any) {
  if (req.method !== "GET") {
    res.status(405).json({ ok: false, error: "Method not allowed" });
    return;
  }

  res.setHeader("content-type", "text/html; charset=utf-8");
  res.status(200).send(studioPage());
}
