function videoPage() {
  return `<!doctype html>
<html lang="sl">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Zora Genesis AI Video</title>
  <style>
    :root{color-scheme:light;--bg:#f5f6f8;--paper:#ffffff;--ink:#17191c;--muted:#68707d;--line:#d9e0ea;--accent:#7a3f2a;--accent2:#146f64;--soft:#f1f5f4;--dark:#121416}
    *{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:linear-gradient(180deg,#eef3f4 0,#f7f8fa 230px,var(--bg) 100%);color:var(--ink);min-height:100vh;position:relative;overflow-x:hidden}
    body:before{content:"";position:fixed;inset:0 0 auto 0;height:172px;pointer-events:none;background:linear-gradient(90deg,rgba(20,111,100,.14) 0 1px,transparent 1px 88px),linear-gradient(180deg,rgba(122,63,42,.12) 0 1px,transparent 1px 46px),linear-gradient(135deg,rgba(255,255,255,.92),rgba(227,239,238,.35));mask-image:linear-gradient(180deg,#000 0,rgba(0,0,0,.72) 54%,transparent 100%)}
    body:after{content:"";position:fixed;right:-70px;top:92px;width:360px;height:520px;pointer-events:none;opacity:.22;background:repeating-linear-gradient(90deg,transparent 0 18px,rgba(20,111,100,.55) 18px 20px),repeating-linear-gradient(180deg,transparent 0 30px,rgba(122,63,42,.36) 30px 32px);clip-path:polygon(18% 0,100% 7%,88% 100%,0 82%)}
    main{position:relative;z-index:1;width:min(1160px,calc(100% - 28px));margin:0 auto;padding:18px 0 34px}header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);margin-bottom:14px}
    h1{margin:0;font-size:clamp(28px,4vw,42px);line-height:1;letter-spacing:0}h2{margin:0;font-size:16px}p{color:var(--muted)}a,button,input,select,textarea{font:inherit}a{color:var(--accent2);text-decoration:none;font-weight:750}
    .layout{position:relative;display:grid;grid-template-columns:minmax(300px,380px) minmax(0,1fr);gap:12px;align-items:start}.layout:before{content:"";position:absolute;left:402px;right:16px;top:18px;height:70px;border-radius:8px;pointer-events:none;background:linear-gradient(90deg,rgba(122,63,42,.18),transparent 48%),repeating-linear-gradient(90deg,rgba(20,111,100,.18) 0 12px,transparent 12px 22px);opacity:.7}.layout:after{content:"";position:absolute;left:410px;right:24px;bottom:20px;height:76px;border-radius:8px;pointer-events:none;background:linear-gradient(90deg,transparent 0 5%,rgba(255,255,255,.75) 5% 7%,transparent 7% 11%),repeating-linear-gradient(90deg,rgba(23,25,28,.08) 0 1px,transparent 1px 34px),linear-gradient(180deg,rgba(20,111,100,.08),transparent);opacity:.75}.panel{position:relative;z-index:1;background:var(--paper);border:1px solid var(--line);border-radius:8px;padding:14px;box-shadow:0 1px 2px rgba(25,23,21,.04)}.controls{display:grid;gap:11px}
    label{display:grid;gap:6px;color:var(--muted);font-size:13px;font-weight:720}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--ink);padding:10px 11px}textarea{min-height:100px;resize:vertical;line-height:1.45}
    .row,.credit-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.credit-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.button-row{display:flex;flex-wrap:wrap;gap:9px}
    button{min-height:42px;border:1px solid var(--accent);border-radius:8px;padding:0 14px;background:var(--accent);color:#fff;font-weight:780;cursor:pointer}button.secondary{background:var(--paper);color:var(--ink);border-color:var(--line)}button:disabled{opacity:.6;cursor:progress}
    .stage{display:grid;place-items:center;min-height:620px;overflow:hidden}.stage:before{content:"";position:absolute;inset:16px;border-radius:8px;pointer-events:none;background:linear-gradient(90deg,rgba(20,111,100,.08) 0 1px,transparent 1px 54px),linear-gradient(180deg,rgba(122,63,42,.07) 0 1px,transparent 1px 54px);mask-image:radial-gradient(circle at 50% 45%,transparent 0 230px,#000 260px)}.canvas-wrap{position:relative;z-index:1;width:min(100%,430px);display:grid;gap:12px;justify-items:center}canvas,video{width:100%;height:auto;border-radius:8px;background:var(--dark);box-shadow:0 18px 50px rgba(25,23,21,.18)}video{display:none}
    .status{color:var(--muted);font-size:14px;text-align:center;min-height:22px}.download{display:none;min-height:42px;align-items:center;justify-content:center;border-radius:8px;padding:0 14px;color:#fff;background:var(--accent2)}.download.show{display:inline-flex}
    .hero-card{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:8px;background:#111;min-height:190px}.hero-card img{display:block;width:100%;height:220px;object-fit:cover}.hero-copy{position:absolute;left:12px;right:12px;bottom:12px;border-radius:8px;background:rgba(18,20,22,.72);backdrop-filter:blur(8px);color:#fff;padding:10px 11px}.hero-copy strong{display:block;font-size:15px}.hero-copy span{display:block;margin-top:3px;color:#dfe6eb;font-size:12px;line-height:1.35}.credit-panel,.credit-card{display:grid;gap:8px;border:1px solid var(--line);border-radius:8px;padding:12px;background:#fff}.credit-card{background:var(--soft);min-height:82px}.credit-card span,.note{color:var(--muted);font-size:12px;line-height:1.4}.lock-note{border:1px solid #f0c8a8;background:#fff8f1;color:#91400f;border-radius:8px;padding:10px 11px;font-size:13px;line-height:1.45}.lock-note a{color:#91400f}
    @media(max-width:880px){header,.layout,.row,.credit-grid{grid-template-columns:1fr}header{align-items:flex-start;flex-direction:column}.stage{min-height:auto}.layout:before,.layout:after,body:after{display:none}}
  </style>
</head>
<body>
  <main>
    <header><div><h1>AI foto v video</h1><p>Naloži sliko, opiši prizor in pripravi video osnutek za Reels, Story ali objavo.</p></div><div class="button-row"><a href="/studio">Studio</a><a href="/preview">Predogled</a></div></header>
    <section class="layout">
      <aside class="panel controls">
        <figure class="hero-card">
          <img src="/assets/fun-studio-video-creator-hero.png" alt="AI video kreator: fotografija se spremeni v vertikalni video za objave" />
          <figcaption class="hero-copy"><strong>Iz fotografije v video osnutek</strong><span>Naloži sliko, opiši gibanje in pripravi vsebino za Reels, Story ali objavo.</span></figcaption>
        </figure>
        <label>Slika<input id="file" type="file" accept="image/*" /></label>
        <div class="row"><label>Format<select id="aspect"><option value="9:16">Reels / Story 9:16</option><option value="1:1">Kvadrat 1:1</option><option value="16:9">Ležeče 16:9</option></select></label><label>Trajanje<select id="duration"><option value="5">5 sekund</option><option value="10">10 sekund</option></select></label></div>
        <div class="row"><label>Tema za govor<input id="speechTopic" placeholder="Npr. ponos, izdaja, denar, zaupanje..." /></label><label>Jezik govora<select id="speechLanguage"><option value="si">SI</option><option value="eng">ENG</option><option value="esp">ESP</option></select></label></div>
        <button id="generateSpeech" class="secondary" type="button">Ustvari govor</button>
        <label>Opis videa<textarea id="prompt" placeholder="Npr. počasen cinematic približek, oseba se nasmehne, topla svetloba, realistično gibanje..."></textarea></label>
        <div class="button-row"><button id="aiVideo" type="button" disabled>Ustvari AI video</button><button id="localExport" class="secondary" type="button">Hiter WebM izvoz</button></div>
        <p class="lock-note" id="videoAccessNotice">AI video je v demo obdobju zaklenjen za uporabnike brez potrjenega nakupa kreditov. Začetnih 50 brezplačnih kreditov ga ne odklene. Lokalni WebM izvoz ostane brezplačen. <a href="/pricing">Kupi kredite</a></p>
        <section class="credit-panel"><h2>Video krediti</h2><div class="credit-grid"><div class="credit-card"><strong>5 sekund</strong><span>Gen-4 Turbo porabi približno 25 kreditov.</span></div><div class="credit-card"><strong>10 sekund</strong><span>Gen-4 Turbo porabi približno 50 kreditov.</span></div><div class="credit-card"><strong>1000 kreditov</strong><span>Približno 40 kratkih 5s testov.</span></div></div><p class="note">Ključ ostane na backendu kot RUNWAYML_API_SECRET. Brskalnik ga nikoli ne vidi.</p></section>
      </aside>
      <section class="panel stage"><div class="canvas-wrap"><canvas id="canvas" width="1080" height="1920"></canvas><video id="video" controls playsinline></video><div class="status" id="status">Naloži sliko in ustvari AI video.</div><a id="download" class="download" download="ai-video.mp4">Prenesi video</a></div></section>
    </section>
  </main>
  <script>
    const file=document.getElementById("file"),aspect=document.getElementById("aspect"),duration=document.getElementById("duration"),prompt=document.getElementById("prompt"),speechTopic=document.getElementById("speechTopic"),speechLanguage=document.getElementById("speechLanguage"),canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d"),video=document.getElementById("video"),status=document.getElementById("status"),download=document.getElementById("download");let image=null,imageDataUrl="";
    const params=new URLSearchParams(window.location.search);if(params.get("topic"))speechTopic.value=params.get("topic");if(params.get("language"))speechLanguage.value=params.get("language");if(params.get("text"))prompt.value=params.get("text");
    function setStatus(v){status.textContent=v}function ratio(){if(aspect.value==="16:9")return"1280:720";if(aspect.value==="1:1")return"960:960";return"720:1280"}function setCanvas(){if(aspect.value==="16:9"){canvas.width=1920;canvas.height=1080}else if(aspect.value==="1:1"){canvas.width=1080;canvas.height=1080}else{canvas.width=1080;canvas.height=1920}draw()}
    function draw(){ctx.fillStyle="#151312";ctx.fillRect(0,0,canvas.width,canvas.height);if(!image){ctx.fillStyle="#efe7de";ctx.font="700 42px Arial,sans-serif";ctx.textAlign="center";ctx.fillText("Naloži sliko",canvas.width/2,canvas.height/2);ctx.textAlign="left";return}const ir=image.width/image.height;let w=canvas.width,h=w/ir;if(h<canvas.height){h=canvas.height;w=h*ir}ctx.drawImage(image,(canvas.width-w)/2,(canvas.height-h)/2,w,h)}
    file.addEventListener("change",()=>{const selected=file.files&&file.files[0];if(!selected)return;const reader=new FileReader();reader.onload=()=>{imageDataUrl=String(reader.result);const img=new Image();img.onload=()=>{image=img;draw();setStatus("Slika pripravljena.")};img.src=imageDataUrl};reader.readAsDataURL(selected)});
    aspect.addEventListener("change",setCanvas);
    document.getElementById("generateSpeech").addEventListener("click",async()=>{const topic=speechTopic.value.trim();if(!topic)return setStatus("Najprej vpiši temo za govor.");const button=document.getElementById("generateSpeech");button.disabled=true;try{setStatus("Ustvarjam govor...");const response=await fetch("/agent/draft",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:topic,language:speechLanguage.value})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"Speech draft failed");prompt.value=data.draft.source.post;setStatus("Govor je pripravljen kot opis videa.")}catch(error){setStatus(error instanceof Error?error.message:String(error))}finally{button.disabled=false}});
    async function poll(id){for(let i=0;i<48;i++){await new Promise((resolve)=>setTimeout(resolve,i<2?2500:5000));const response=await fetch("/api/video/task?id="+encodeURIComponent(id));const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"Video status failed");const task=data.task;setStatus("Runway: "+(task.status||"processing")+(task.progress?" "+Math.round(task.progress*100)+"%":""));if(task.status==="SUCCEEDED"&&task.output?.[0])return task.output[0];if(task.status==="FAILED"||task.status==="CANCELED")throw new Error("AI video ni uspel: "+task.status)}throw new Error("Video se predolgo ustvarja.")}
    document.getElementById("aiVideo").addEventListener("click",async()=>{if(!imageDataUrl)return setStatus("Najprej naloži sliko.");const button=document.getElementById("aiVideo");button.disabled=true;video.style.display="none";download.classList.remove("show");try{setStatus("Pošiljam v Runway...");const response=await fetch("/api/video/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"gen4_turbo",promptImage:imageDataUrl,promptText:prompt.value.trim()||"Subtle cinematic movement, natural light, realistic social media video.",ratio:ratio(),duration:Number(duration.value)})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"AI video generation failed");setStatus("Runway task sprejet. Cena: "+(data.task.estimatedCost?.credits||"?")+" kreditov.");const url=await poll(data.task.id);video.src=url;video.style.display="block";download.href=url;download.classList.add("show");setStatus("AI video je pripravljen.")}catch(error){setStatus(error instanceof Error?error.message:String(error))}finally{button.disabled=false}});
    document.getElementById("localExport").addEventListener("click",()=>{if(!image)return setStatus("Najprej naloži sliko.");const stream=canvas.captureStream(30),recorder=new MediaRecorder(stream,{mimeType:"video/webm;codecs=vp9"}),chunks=[];recorder.ondataavailable=(event)=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=()=>{const blob=new Blob(chunks,{type:"video/webm"});download.href=URL.createObjectURL(blob);download.download="hitri-video.webm";download.classList.add("show");setStatus("WebM pripravljen.")};recorder.start();setTimeout(()=>recorder.stop(),Number(duration.value)*1000);setStatus("Izvažam WebM...")});
    setCanvas();
    const videoAccessCopy=params.get("language")==="eng"?["AI video requires a confirmed credit purchase. Free trial credits do not unlock it. Local WebM export remains free.","AI video unlocked. Generating a video uses credits."]:params.get("language")==="esp"?["El vídeo con IA requiere una compra de créditos confirmada. Los créditos gratuitos no lo desbloquean. La exportación WebM local sigue siendo gratuita.","Vídeo con IA desbloqueado. Generar un vídeo consume créditos."]:["AI video se odklene po potrjenem nakupu kreditov. Začetnih 50 brezplačnih kreditov ga ne odklene. Lokalni WebM izvoz ostane brezplačen.","AI video je odklenjen. Generiranje porablja kredite."];
    document.getElementById("videoAccessNotice").firstChild.textContent=videoAccessCopy[0]+" ";
    fetch("/auth/status").then((response)=>{if(!response.ok)throw new Error("Access check failed");return response.json()}).then((data)=>{document.getElementById("aiVideo").disabled=!data.videoAccess;if(data.videoAccess)document.getElementById("videoAccessNotice").firstChild.textContent=videoAccessCopy[1]+" "}).catch(()=>{document.getElementById("aiVideo").disabled=true});
    if(params.get("from")==="studio"){const transferred=sessionStorage.getItem("zg_video_image");if(transferred&&transferred.startsWith("data:image/")){const img=new Image();img.onload=()=>{image=img;imageDataUrl=transferred;draw();sessionStorage.removeItem("zg_video_image");setStatus("Slika iz Studia je pripravljena.")};img.onerror=()=>setStatus("Slike ni bilo mogoče prenesti. Naloži jo ročno.");img.src=transferred}}
  </script>
</body>
</html>`;
}

export default function handler(req: any, res: any) {
  if (req.method !== "GET") {
    res.status(405).json({ ok: false, error: "Method not allowed" });
    return;
  }

  res.setHeader("content-type", "text/html; charset=utf-8");
  res.status(200).send(videoPage());
}
